### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by pamela-drouin** [trussworks/research-design-playbook#14]
Hi there, I bumped into your website while looking at various research/design playbooks. I found a small typo in this section:
https://playbook.truss.design/docs/resources/a11y-inclusion/#tools-to-test-accessibility

In the link text for `Color contract analyzer`, I believe it should be `contrast`.

That's all, thank you so much!

**Comment by rpdelaney** [comment]
Looks like this was fixed in 852441da. Thank you for reporting this!
